name: CI Build Action
description: Build Python application artifacts

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Restore pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ runner.os }}-${{ hashFiles('python-app/requirements.txt') }}

    - name: Install dependencies
      shell: bash
      working-directory: python-app
      run: |
        pip install -r requirements.txt

    - name: Build application
      shell: bash
      working-directory: python-app
      run: |
        pip install build
        python -m build
