name: Day 6 + Day 7 Demo – Outputs, Artifacts & Caching

on:
  workflow_dispatch:

jobs:
  ci:
    name: CI Job (Build, Cache & Produce Artifact)
    runs-on: ubuntu-latest

    outputs:
      artifact_name: ${{ steps.meta.outputs.artifact_name }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      # ---------------- CONTROL DATA (DAY 6) ----------------
      - name: Create step output
        id: meta
        run: |
          echo "artifact_name=python-build" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ---------------- CACHE RESTORE (DAY 7) ----------------
      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('python-app/requirements.txt') }}-demo-v5
          restore-keys: |
            pip-cache-${{ runner.os }}-demo-v5

      # ---------------- DEPENDENCY INSTALL ----------------
      - name: Install dependencies
        id: install_deps
        working-directory: python-app
        run: pip install -r requirements.txt

      # ---------------- TOOL INSTALL ----------------
      - name: Install Python build tool
        run: pip install build

      # ---------------- BUILD ----------------
      - name: Build application
        id: app-build
        if: ${{ steps.install_deps.outcome == 'success' }}
        working-directory: python-app
        run: python -m build

      # ---------------- ARTIFACT (DAY 6) ----------------
      - name: Upload artifact
        if: ${{ steps.app-build.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.artifact_name }}
          path: python-app/dist
          retention-days: 3

  cd:
    name: CD Job (Consume CI Artifact)
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from CI – Demo
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.ci.outputs.artifact_name }}
          path: cd-input

      - name: Inspect artifact
        run: |
          echo "Artifact received by CD:"
          ls -R cd-input