name: Day 6 Demo – CD Consuming CI Artifact

on:
  workflow_run:
    workflows:
      - "Artifacts_Outputs_Demo_CI"
    types:
      - completed

jobs:
  consume-artifact:
    name: Consume CI Artifact (CD Demo)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Show CI run context
        run: |
          echo "CI Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "CI Head SHA: ${{ github.event.workflow_run.head_sha }}"

      - name: List artifacts from CI run
        uses: actions/github-script@v7
        id: list
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            console.log(artifacts.data.artifacts.map(a => a.name));
            core.setOutput("artifact_name", artifacts.data.artifacts[0].name);

      - name: Download artifact from CI run
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: ${{ steps.list.outputs.artifact_name }}
          path: cd-input

      - name: Inspect downloaded artifact
        run: |
          echo "Artifact received by CD:"
          ls -R cd-input
