name: CD Demo (Reusable CI & CD)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: Run Reusable CI
    uses: ./.github/workflows/reusable-ci.yml

  cd:
    name: Run Reusable CD
    needs: ci
    uses: ./.github/workflows/reusable-cd.yml
    with:
      artifact_name: ${{ needs.ci.outputs.artifact_name }}
      environment: dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
