name: CI - Validation

on:
  pull_request:
    branches:
      - dev
      - stage
      - main

permissions:
  contents: read

jobs:
  ci:
    name: CI - Source code validation
    runs-on: ubuntu-latest
    
    steps: 
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('python-app/requirements.txt') }}
          
      - name: Dependency Installation
        working-directory: python-app
        run: pip install -r requirements.txt

      - name: Python Linting
        working-directory: python-app
        run: |
          pip install flake8
          flake8 .
          
      - name: Python Unit Testing
        working-directory: python-app
        run: |
          pip install pytest
          pytest --junitxl=test-results.xml
          
      - name: Upload CI results
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-results-${{ github.event.pull_request.head.sha }}
          path: python-app/test-results.xml
          retention-days: 10   
