name: Reusable CD - Deploy Artifact to S3

on:
  workflow_call:
    inputs:
      artifact_name:
        description: Artifact name produced by CI
        required: true
        type: string
      environment:
        description: Target deployment environment
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        description: AWS IAM role for OIDC
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  cd:
    name: CD - Deploy to S3
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: cd-input

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync cd-input/ \
            s3://${{ vars.S3_BUCKET_NAME }}/python/ \
            --delete
